export const products = [
    {
        id: 1,
        title: "Polera Blanca",
        description: "Polera manga corta color blanco, hecha de algodón 100%.",
        price: "$11.990",
        imageUrl: "/FotosPoleras/Foto Polera Blanca.jpg",
        sizes: ["S", "M", "L"],
    },
    {
        id: 2,
        title: "Polera Negra",
        description: "Polera manga corta color negro, hecha de algodon 100%",
        price: "$11.990",
        imageUrl:  "/FotosPoleras/PoleraNegra.jpg",
        sizes: ["S", "M", "L"],
    },
    {
        id: 3,
        title: "Poleron Oversize Verde Botella",
        description: "Poleron Oversize 100% algodon ",
        price: "$30.000",
        imageUrl:  "/FotosPolerones/1.jpg",
        sizes: ["S", "M", "L"],
    },
    {
        id: 4,
        title: "Poleron Oversize Negro",
        description: "Poleron Oversize 100% algodon ",
        price: "$30.000",
        imageUrl:  "/FotosPolerones/2.jpg",
        sizes: ["S", "M", "L"],
    },
    {
        id: 5,
        title: "Producto 4",
        description: "Descripción del producto 4",
        price: "$25.00",
        imageUrl: "/FotosPoleras/Foto Polera Blanca.jpg",
        sizes: ["S", "M", "L"],
    },
    {
        id: 6,
        title: "Producto 5",
        description: "Descripción del producto 5",
        price: "$25.00",
        imageUrl:  "/FotosPoleras/Foto Polera Blanca.jpg",
        sizes: ["S", "M", "L"],
    },
    {
        id: 7,
        title: "Producto 6",
        description: "Descripción del producto 6",
        price: "$25.00",
        imageUrl:  "/FotosPoleras/Foto Polera Blanca.jpg",
        sizes: ["S", "M", "L"],
    },
    {
        id: 8,
        title: "Producto 7",
        description: "Descripción del producto 7",
        price: "$25.00",
        imageUrl:  "/FotosPoleras/Foto Polera Blanca.jpg",
        sizes: ["S", "M", "L"],
    },
    {
        id: 9,
        title: "Producto 8",
        description: "Descripción del producto 8",
        price: "$25.00",
        imageUrl:  "/FotosPoleras/Foto Polera Blanca.jpg",
        sizes: ["S", "M", "L"],
    },
    {
        id: 10,
        title: "Producto 9",
        description: "Descripción del producto 9",
        price: "$25.00",
        imageUrl:  "/FotosPoleras/Foto Polera Blanca.jpg",
        sizes: ["S", "M", "L"],
    },
    // Otros productos...
];

export const secciones = [
    { nombre: "INICIO", url: "/" },
    { nombre: "PRODUCTOS", url: "/product" },
    {
        nombre: "CONTACTO",
        url: "https://www.instagram.com/bsheep.cl",
        externo: true,
    },
    { nombre: "GUIA DE TALLAS", url: "#" },
];